- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Install python docker module
  apt:
    name: python3-docker
    state: present
